#!/usr/bin/with-contenv bash

mkdir -p /config/rclone

# For backwards compatibility
[[ -f "/root/.config/rclone/rclone.conf" ]] && \
    echo "DEPRECATED: Copying rclone conf from /root/.config/rclone/rclone.conf, please change your mount to /config/rclone/rclone.conf"
    cp \
        /root/.config/rclone/rclone.conf \
        /config/rclone/rclone.conf

# default config file
[[ ! -f "/config/rclone/rclone.conf" ]] && \
    mkdir -p /config/rclone && \
    cp \
        /defaults/rclone.conf \
        /config/rclone/rclone.conf

chown -R abc:abc \
  /config

chown -R abc:abc \
  /data
