#!/usr/bin/with-contenv bash


export RCLONE_CONFIG=/config/rclone/rclone.conf
echo $VERBOSITY
[[ -n "$VERBOSITY" ]] && export VERBOSITY_ARG=-$VERBOSITY || export VERBOSITY_ARG=""

exec \
    s6-setuidgid abc unifi-protect-backup ${VERBOSITY_ARG}
